# https://docs.travis-ci.com/user/languages/minimal-and-generic/
language: minimal
dist: bionic

# no install step to perform
install: true

# When a script command fails, travis run the next one so we must use
# `travis_terminate 1`
script:
  - >
    cd ci
    && make env
    || travis_terminate 1

  - >
    cd ci
    && make devel
    || travis_terminate 1

  - >
    cd ci
    && make build
    || travis_terminate 1

  - >
    cd ci
    && make prod
    || travis_terminate 1
