name: Linux

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install Qt5
      run: |
        sudo apt update -q
        sudo apt install -yq qtbase5-dev
    - uses: actions/checkout@v3
    - name: Configure
      run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build --target all -v
    - name: Test
      run: cmake --build build --target test -v
    - name: Install
      run: cmake --build build --target install -v -- DESTDIR=install
