name: MacOS

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Install Qt5
      run: brew install qt
    - uses: actions/checkout@v2
    - name: Configure
      run: cmake -S. -Bbuild -G "Xcode" -DCMAKE_CONFIGURATION_TYPES=Release
    - name: Build
      run: cmake --build build --config Release --target all -v
    - name: Test
      run: cmake --build build --config Release --target test -v
    - name: Install
      run: cmake --build build --config Release --target install -v
