name: MacOS

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Install Qt6
      run: |
        brew install qt@6;
        echo "/usr/local/opt/qt@5/bin" >> $GITHUB_PATH
    - uses: actions/checkout@v3
    - name: Configure
      run: cmake -S. -Bbuild -G "Xcode" -DCMAKE_CONFIGURATION_TYPES=Release
    - name: Build
      run: cmake --build build --config Release --target ALL_BUILD -v
    - name: Test
      run: cmake --build build --config Release --target RUN_TESTS -v
    - name: Install
      run: cmake --build build --config Release --target install -v
