name: Windows

on: [push, pull_request, workflow_dispatch]

jobs:
  # Building using the github runner environement directly.
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Install Qt6
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.*
    - uses: actions/checkout@v4
    - name: Configure
      run: cmake -S. -Bbuild -G "Visual Studio 17 2022" -DCMAKE_CONFIGURATION_TYPES=Release
    - name: Build
      run: cmake --build build --config Release --target ALL_BUILD -v -- /maxcpucount
    - name: Test
      run: cmake --build build --config Release --target RUN_TESTS -v -- /maxcpucount
    - name: Install
      run: cmake --build build --config Release --target INSTALL -v -- /maxcpucount
